### ISSUE TITLE
Deployment failed "The Open Liberty Operator is not available"

### ISSUE THREAD

**Issue by m-reza-rahman** [WASdev/azure.liberty.aro#60]
Simple deployment without an application randomly fails:

{

"status": "failed",

"error": {

"code": "DeploymentScriptError",

"message": "The provided script failed with multiple errors. First error:\r\nNo resources found in openshift-operators namespace.. Please refer to https://aka.ms/DeploymentScriptsTroubleshoot for more deployment script information.",

"details": [

{

"code": "DeploymentScriptError",

"message": "No resources found in openshift-operators namespace."

},

{

"code": "DeploymentScriptError",

"message": "No resources found in openshift-operators namespace."

},

{

"code": "DeploymentScriptError",

"message": "No resources found in openshift-operators namespace."

},

{

"code": "DeploymentScriptError",

"message": "No resources found in openshift-operators namespace."

},

{

"code": "DeploymentScriptError",

"message": "No resources found in openshift-operators namespace."

},

{

"code": "DeploymentScriptError",

"message": "No resources found in openshift-operators namespace."

},

{

"code": "DeploymentScriptError",

"message": "The Open Liberty Operator is not available."

}

]

}

}

**Comment by majguo** [comment]
The error message indicated that [the Open Liberty Operator is not available](https://github.com/WASdev/azure.liberty.aro/blob/main/src/main/scripts/install.sh#L202-L206) after [trying 99 times](https://github.com/WASdev/azure.liberty.aro/blob/main/src/main/scripts/install.sh#L93-L137) with:
```
oc get deployment olo-controller-manager -n openshift-operators
```

As the Open Liberty Operator is **indirectly**  installed by OLM (Operator Lifecycle Manager) (see [Installing from OperatorHub using the CLI](https://docs.openshift.com/container-platform/4.10/operators/admin/olm-adding-operators-to-cluster.html#olm-installing-operator-from-operatorhub-using-cli_olm-adding-operators-to-a-cluster)) instead of being installed using kustomize/kubectl **directly** (see [Open Liberty Operator 0.8.0 installation guide](https://github.com/OpenLiberty/open-liberty-operator/tree/main/deploy/releases/0.8.0#installation)), it's possible that the Open Liberty Operator is still not available after the current maximum retry times (99) for some edge cases.

So the fix is to increase the maximum retry times to 299, which is ~3 times of the current value, to mitigate the issue. We'll monitor if the issue won't be reproduced after change, then decide the appropriate action if it happens again, e.g., increase to a bigger value or make it an infinitely loop.

**Comment by edburns** [comment]
Hello, @majguo and the team discussed this in the stand up today. We agreed on the following plan.

1. Apply this workaround to increase NUM_RETRIES.
2. Notify Paul Czarkowski of our need to do this workaround. Surely this many retries should not be necessary.
