### ISSUE TITLE
Install Open Liberty Operator from Red Hat’s Certified Catalog

### ISSUE THREAD

**Issue by git4rk** [WASdev/azure.liberty.aro#69]
- Currently ARO offering installs OLO from the Operator Hub
- The integrated Operator Hub on OCP uses the Red Hat’s Certified Catalog. This catalog is added out-of-the-box on OCP.
- OLO should be installed from Red Hat’s Certified Catalog.

**Comment by edburns** [comment]
Please assign this to @edburns .

**Comment by majguo** [comment]
I think the ARO offering has already used the integrated Operator Hub to install OLO, instead of the Operator Hub:

- Installing from the integrated Operator Hub (**0.8.1** latest):
  ![image](https://user-images.githubusercontent.com/10357495/183770624-48d1ba5c-b568-432f-a053-a955abe1ebb6.png)
- Installing from https://operatorhub.io/operator/open-liberty (**0.7.0** latest)
  ![image](https://user-images.githubusercontent.com/10357495/183770684-bacea734-aa67-4622-bcef-823bbe811835.png)

The current version of OLO installed in ARO offering is `0.8.0`, which demonstrates that it's installed from the integrated Operator Hub on OCP which uses the Red Hat’s Certified Catalog.

The reason why I used term "Operator Hub" (which caused the confusion) is because it's the name displayed in ARO web console:
![image](https://user-images.githubusercontent.com/10357495/183771677-ce5ff905-b589-4851-a248-4293337c7e3c.png)

As a result, I think the issue can be closed.

**Comment by git4rk** [comment]
From WLO Dev team: The process to publish operators to integrated OperatorHub (RH Certified Catalog) changed recently. We are looking into the new process to publish OLO 0.8.2.

**Comment by git4rk** [comment]
Closing this since we do not need to make any updated. We are waiting RH Catalog to be updated.
